### PR TITLE
Migrate to null safety

### PR DESCRIPTION
**Pull request by pumuckelo**
Hello,

I updated all dependencies and used the dart migration tool.

Not really sure how to correctly test it though

### CODE REVIEW

**Comment by humblerookie** [comment]
@pumuckelo  I'll be checking this week and merging if all looks well, thanks for this upgrade.

**Comment by humblerookie** [comment]
@pumuckelo  can you run the migration against the example subproject as well?. I'll merge this once done

**Comment by HIHIQY1** [comment]
Any update on this?

**Comment by Termtime** [comment]
Interested in the progress of this as well

**Comment by humblerookie** [comment]
Since this PR was taking time, I've migrated here. Thanks @pumuckelo for initiating this. https://github.com/humblerookie/optimized_cached_image/pull/52

**Pull request closed without merging**
